---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
      - name: {{ .Release.Name }}-mysql
        image: {{ .Values.images.mysql.image }}:{{ .Values.images.mysql.tag }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: eoloplantsDB
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: {{ .Release.Name }}-datadb
      volumes:
      - name: {{ .Release.Name }}-datadb
        persistentVolumeClaim:
          # No se crean porque se asume que ya están creados. En este caso, 
          # se debera poder especificar la storageclass de cada servicio que lo necesita
{{- if .Values.persistance.enabled -}}      
          claimName: {{ .Release.Name }}-mysql-pvc
{{- else }}
          claimName: {{ .Values.persistance.mysql | quote }}
{{- end }}          
---
# Se crean los PersistenceVolumes (opcion por defecto)
# Se crean de forma dinámica usando el StorageClass por defecto de la plataforma
{{- if .Values.persistance.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
spec:
  storageClassName: {{ .Release.Name }}-mysql
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql-port
  selector:
    app: {{ .Release.Name }}-mysql
  type: ClusterIP
---
{{- if .Values.policies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mysql-from-server
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-server
    ports:
    - port: 3306
      protocol: TCP
{{- end}}